### ISSUE TITLE
Display remaining bullets in gun

### ISSUE THREAD

**Issue by notAmritpal** [rm21845/themysterymachine#31]
Should have a visual representation of the number of bullets remaining in the gun or should automatically reload when gun is empty.

**Comment by natebud** [comment]
We're going to expand on this in the future, the current laser look of all weapons is only for debug purposes until we add sound and effects to each weapon.
The ammo count will be displayed on the bottom left of the HUD.

**Comment by ontheloosewu** [comment]
Closed. First part is implemented and second part is a quality of life change (not necessarily needed).
