### ISSUE TITLE
BUG: Can get out of the map and fall indefinitely

### ISSUE THREAD

**Issue by Daniel-Re7** [rm21845/themysterymachine#33]
**Minor Bug**: You can jump off of the rooftops, and when you follow the outer perimeter wall, there is a single hole that you can walk through. Upon walking through, you can walk to the edge of the map and jump off where you will fall indefinitely until you restart the game.

**Comment by natebud** [comment]
We will touch up geometry of map. Player won't be able reach ground floor without dying when fall damage is implemented.

**Comment by natebud** [comment]
Fall Damage added to game. Player is now killed when he falls off of rooftops.
