### ISSUE TITLE
Ammo Capacity Visual Representation

### ISSUE THREAD

**Issue by rm21845** [rm21845/themysterymachine#34]
Add a visual representation of ammo capacity on the left hand slider. The slider should decrement as bullets are shot out. An integer variable can be used for the ammo capacity.

**Comment by RedwanIbneSerajKhan** [comment]
Hey Guys,
I have made a pull request here: https://github.com/rm21845/themysterymachine/pull/35

Here is a video of the running software: https://youtu.be/uZ9yNOrEpv8

Here is a link to my drive with the uploaded files: https://drive.google.com/open?id=1C18RG9_-8-TtmywZJUZORKcuqYGurX01

Hope you are satisfied with my work!

**Comment by natebud** [comment]
We are satisfied.
