### ISSUE TITLE
[Alpha Testing] Bug: When an enemy is destroyed the player is moved.

### ISSUE THREAD

**Issue by joshuaemer** [rm21845/themysterymachine#48]
Operating System: Windows 10

Description: 
When I shoot an enemy the player is moved to the middle of the platform without pressing any controls to move the player.

How to reproduce:
After the player spawns jump onto the ledge to the left. Shoot any enemy and the player will automatically be moved to the middle of the platform.

**Comment by natebud** [comment]
This is the primary feature of the game. You possess the last enemy you shot.
