### ISSUE TITLE
Opening options screen discards settings applied by Unity launcher

### ISSUE THREAD

**Issue by briankarUB** [rm21845/themysterymachine#51]
When the options screen is opened, it seems to load a default set of options and immediately apply them, as opposed to using the options configured by the Unity launcher.

**Reproduction:**
1. Start the game and change to windowed, with a resolution other than the native/default resolution.
2. Open the options screen.

You will see that the game will set its resolution to (presumably) the screen's native resolution. This was tested on a 1920x1080 screen, so in my case it was set to 1920x1080

Tested on the build at https://drive.google.com/open?id=15lvYAxlOVIL975HNi_AyEtWGNqyAQ8RU

**Comment by ontheloosewu** [comment]
Fixed.
