### ISSUE TITLE
Cursor Shows Over Crosshairs

### ISSUE THREAD

**Issue by zackrb4** [rm21845/themysterymachine#53]
Description: Upon receiving a game over and selecting the retry option, the cursor is not hidden.

How to Replicate: 
  1. Start the game normally (open the executable file, select play on the settings menu)
  2. From the main menu, click play, and then click on either level.
  3. Pick up the gun in front of the character by walking up to it, aiming the cross hairs on it, and pressing "E"
  4. Shoot the enemy nearby the character repeatedly until the player becomes the shot character.
  5. Repeatedly shoot the dead body until the player gets a game over screen.
  6. Click on "Restart"

Actual Outcome: The mouse will show on top of the cross hairs

Expected Outcome: The mouse should be hidden when the game restarts.

**Comment by ontheloosewu** [comment]
Fixed.
