### ISSUE TITLE
[feature request] I want to see how many ammo remain.

### ISSUE THREAD

**Issue by jaimeenahn** [rm21845/themysterymachine#55]
When I test, I tried to shoot enemy but because of lack of ammo the shoot doesn't work. I think it will be better if you display remain ammo on somewhere there or reload message like "RELOAD! RELOAD!"

![capture](https://user-images.githubusercontent.com/32367255/39056669-5c659888-4485-11e8-9325-2d72558abfc7.JPG)

**Comment by natebud** [comment]
The ammo bar turned into one of our collaboration tasks so it will be implemented shortly.

**Comment by ontheloosewu** [comment]
Closed, has been implemented.
